### ISSUE TITLE
Empty `it` throws an error

### ISSUE THREAD

**Issue by sjelin** [angular/jasminewd#27]
See https://github.com/angular/protractor/issues/1852

Reproduced with the following commands in a node shell:
```js
var JasmineRunner = require('jasmine');
var jrunner = new JasmineRunner();
require('jasminewd2');
jrunner.addSpecFile('~/sandbox/spec.js')
jrunner.execute();
```
Where `~/sandbox/spec.js` is as follows:
```js
describe("hello", function() {
  it("world");
});
```
This produces the message:
```
Started
F

Failures:
1) hello encountered a declaration exception
  Message:
    Error: undefined is not a function
  Stack:
    Error: undefined is not a function
        at Error (native)
        at validateFunction (~/protractor/node_modules/jasminewd2/index.js:32:36)
        at ~/protractor/node_modules/jasminewd2/index.js:111:16
        at Suite.<anonymous> (~/sandbox/spec.js:2:3)
        at Object.<anonymous> (~/sandbox/spec.js:1:63)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
```
Removing `require('jasminewd2');` gets rid of the error

**Comment by sjelin** [comment]
The error appears to be basically that our validation code is wrong.  We see `undefined` and throw an error, where as we should just ignore it.

**Comment by sporkthrower** [comment]
This also impacts tests marked pending with the Jasmine2 pending() function:

Spec with `pending(' pending fix for platform display DR13-488');` in its body produces the following output.

```
F

Failures:
1)  app detail app info bar will display the platform if available
  Message:
    Failed: => marked Pending pending fix for platform display DR13-488
  Stack:
    Error: Failed: => marked Pending pending fix for platform display DR13-488
```

**Comment by juliemr** [comment]
I have a fix for the empty `it` issue, that's rather easy.

Getting `pending` to work is tougher, because it doesn't play well with asynchronous tests. The way that Jasmine implements `pending` is `throw specialString` and then it searches for that specialString when catching errors. However, this all only works if the error is thrown in the same turn of the event loop. 

But because we're running everything async, by the time we get the `specialString` error, it's already the next turn, and it's too late to throw the error on to Jasmine. 

I'm looking into whether we can force Jasmine to mark the spec as pending in some other way.

**Comment by juliemr** [comment]
In the current Jasmine version, there's no way to mark a spec as pending if it's already running asynchronously, which is how jasminewd always runs specs (inside their own `controlFlow#execute` block). Filed a Jasmine feature request at https://github.com/jasmine/jasmine/issues/937 - but I'm aware that this is probably a strange use case for the `pending` feature.

**Comment by juliemr** [comment]
Made pending its own issue - https://github.com/angular/jasminewd/issues/32

**Comment by juliemr** [comment]
Closed with https://github.com/angular/jasminewd/pull/31
